### ISSUE TITLE
What does it mean?!?!?

### ISSUE THREAD

**Issue by coreytcallaghan** [coreytcallaghan/intra_specific_urban_tolerance#6] opened 2021-10-28 14:53 UTC
So I was wrong and the regular 'median' of a species' observations WAS in the dataframe I had in front of me. Just took me looking through a different R script to realize it.

Anyway, based on our discussions.

Here we have the current standard deviation of the "adjusted Urban Tolerance (median-median)":

![image](https://user-images.githubusercontent.com/28123686/139280910-caa1115c-3de2-47b4-bfeb-65df2f9510f2.png)

Here we have the standard deviation of the "unadjusted Urban Tolerance (just the median of a species' observations)":

![image](https://user-images.githubusercontent.com/28123686/139281149-ea4c3a91-8f72-40db-b503-bc9c3536e9a4.png)

And for context, here we have the standard deviation of the "unadjusted" versus the standard deviation of the "adjusted" urban tolerance:

![image](https://user-images.githubusercontent.com/28123686/139281347-6fe5b86a-0208-4395-9b10-8077e0e1b5b6.png)

AND, with the 'unadjusted urban tolerance', we can calculate CV of it, as well as CV of buffer level urbanization, which I did just for kicks, and the relationship remains similar:

![image](https://user-images.githubusercontent.com/28123686/139281558-5dbb99ec-051b-4144-a43b-271c4cb0766c.png)

**Comment by coreytcallaghan** [comment] 2021-10-28 14:55
I guess the take away here is that for plots 1 and 2, the relationship (```geom_smooth(method="lm")```) remains strong regardless of how urban tolerance is calculated within a buffer. But it does differ from the 1:1 line (red dashed line).

Need to think about what this means still a little bit.

**Comment by bowlerbear** [comment] 2021-10-29 07:09
well this is reassuring though! that strong relationship is not just caused by having median sampled urban on x and y.
We get it without that. Phews.
But now we have a choice! on the one hand. i feel the adjustment makes the analysis a bit harder to interpret. on the other hand, maybe it is necessary. Since to me urban tolerance should be defined along the lines of probability to use urban habitat -which is urban use/urban available.

But trying to interpret the unadjusted ones. Points under the line more variability in sampled urban versus used urban - so are more fixed in their urban use. So it makes sense to me that more points are below the line, since most species are urban avoiders. Points on the line are species that are doing more of the urban tracking?? using more urban areas when it is more available??

Anyway, I will look at the other code.

Tbh, I would do a tiny dummy simulation to check my intuition in these cases. Assuming a species fixed in its urban use and another more flexible one.

**Closed as completed** 2022-07-29 09:17 UTC
